// src/templates/resumeTemplates.js

export const TEMPLATES = {
  'modern-dark': {
    name: 'Modern Dark',
    preview: '🌑',
    desc: 'Dark sidebar, gradient header',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',sans-serif; display:flex; min-height:100vh; background:#0f0f0f; }
  .sidebar { width:300px; background:linear-gradient(180deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%); padding:32px 24px; display:flex; flex-direction:column; gap:24px; }
  .photo-wrap { text-align:center; }
  .photo-wrap img { width:110px; height:110px; border-radius:50%; object-fit:cover; border:3px solid #7c3aed; }
  .photo-placeholder { width:110px; height:110px; border-radius:50%; background:rgba(124,58,237,0.3); display:flex; align-items:center; justify-content:center; margin:0 auto; font-size:36px; }
  .name { font-size:22px; font-weight:800; color:#fff; text-align:center; margin-top:12px; }
  .role { font-size:13px; color:#a78bfa; text-align:center; margin-top:4px; font-weight:500; }
  .divider { height:1px; background:rgba(255,255,255,0.1); }
  .section-title { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#7c3aed; margin-bottom:10px; }
  .contact-item { font-size:12px; color:#cbd5e1; margin-bottom:6px; display:flex; align-items:center; gap:8px; }
  .skill-tag { display:inline-block; padding:4px 10px; background:rgba(124,58,237,0.3); color:#a78bfa; border-radius:12px; font-size:11px; margin:3px 2px; border:1px solid rgba(124,58,237,0.4); }
  .edu-item { margin-bottom:10px; }
  .edu-degree { font-size:12px; font-weight:600; color:#e2e8f0; }
  .edu-school { font-size:11px; color:#94a3b8; }
  .main { flex:1; background:#f8fafc; padding:40px 36px; }
  .summary-box { background:linear-gradient(135deg,#ede9fe,#ddd6fe); border-left:4px solid #7c3aed; padding:16px 20px; border-radius:0 12px 12px 0; margin-bottom:28px; }
  .summary-box p { font-size:13px; color:#4c1d95; line-height:1.8; font-style:italic; }
  .main-section { margin-bottom:28px; }
  .main-title { font-size:14px; font-weight:800; color:#1e293b; text-transform:uppercase; letter-spacing:1.5px; border-bottom:2px solid #7c3aed; padding-bottom:6px; margin-bottom:14px; }
  .exp-item { margin-bottom:14px; }
  .exp-role { font-size:14px; font-weight:700; color:#1e293b; }
  .exp-company { font-size:12px; color:#7c3aed; font-weight:600; }
  .exp-text { font-size:12px; color:#475569; line-height:1.7; margin-top:4px; }
  ul.bullets { padding-left:16px; }
  ul.bullets li { font-size:12px; color:#475569; line-height:1.7; margin-bottom:4px; }
  .footer { background:#1a1a2e; color:#94a3b8; text-align:center; padding:10px; font-size:10px; }
</style>
</head>
<body>
<div style="display:flex;flex-direction:column;width:100%;">
<div style="display:flex;flex:1;">
<div class="sidebar">
  <div class="photo-wrap">
    ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="photo-placeholder">👤</div>`}
    <div class="name">${d.name}</div>
    <div class="role">${d.role}</div>
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Contact</div>
    ${d.email ? `<div class="contact-item">📧 ${d.email}</div>` : ''}
    ${d.phone ? `<div class="contact-item">📱 ${d.phone}</div>` : ''}
    ${d.linkedin ? `<div class="contact-item">💼 ${d.linkedin}</div>` : ''}
    ${d.github ? `<div class="contact-item">🐙 ${d.github}</div>` : ''}
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Skills</div>
    ${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Education</div>
    ${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}
  </div>
</div>
<div class="main">
  ${d.summary ? `<div class="summary-box"><p>${d.summary}</p></div>` : ''}
  ${d.experience.length ? `
  <div class="main-section">
    <div class="main-title">Experience</div>
    ${d.experience.map(e => `<div class="exp-item"><div class="exp-role">${e.title}</div><div class="exp-company">${e.company}</div><div class="exp-text">${e.description}</div></div>`).join('')}
  </div>` : ''}
  ${d.projects.length ? `
  <div class="main-section">
    <div class="main-title">Projects</div>
    ${d.projects.map(p => `<div class="exp-item"><div class="exp-role">${p.name}</div><div class="exp-text">${p.description}</div></div>`).join('')}
  </div>` : ''}
  ${d.extra ? `<div class="main-section"><div class="main-title">Additional</div><div class="exp-text">${d.extra}</div></div>` : ''}
</div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</div>
</body></html>`
  },

  'minimal-white': {
    name: 'Minimal White',
    preview: '⬜',
    desc: 'Clean, ATS-friendly',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Lato',sans-serif; background:#fff; color:#2d3748; max-width:860px; margin:0 auto; padding:48px 52px; }
  .header { border-bottom:3px solid #2d3748; padding-bottom:20px; margin-bottom:28px; display:flex; align-items:center; gap:24px; }
  .header img { width:90px; height:90px; border-radius:50%; object-fit:cover; }
  .header-text h1 { font-size:32px; font-weight:900; color:#1a202c; letter-spacing:-0.5px; }
  .header-text .role { font-size:16px; color:#718096; font-weight:300; margin-top:4px; }
  .header-text .contacts { display:flex; gap:16px; margin-top:8px; flex-wrap:wrap; }
  .header-text .contacts span { font-size:12px; color:#4a5568; }
  .section { margin-bottom:24px; }
  .section-title { font-size:11px; font-weight:900; text-transform:uppercase; letter-spacing:3px; color:#718096; margin-bottom:12px; }
  .summary { font-size:13px; line-height:1.8; color:#4a5568; }
  .skill-tag { display:inline-block; padding:3px 10px; border:1px solid #cbd5e0; border-radius:4px; font-size:12px; color:#4a5568; margin:3px 2px; }
  .item { margin-bottom:14px; padding-bottom:14px; border-bottom:1px solid #edf2f7; }
  .item:last-child { border-bottom:none; }
  .item-title { font-size:14px; font-weight:700; color:#2d3748; }
  .item-sub { font-size:12px; color:#718096; margin-top:2px; }
  .item-text { font-size:12px; color:#4a5568; line-height:1.7; margin-top:6px; }
  .footer { border-top:1px solid #e2e8f0; margin-top:32px; padding-top:10px; text-align:center; font-size:10px; color:#a0aec0; }
</style>
</head>
<body>
<div class="header">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : ''}
  <div class="header-text">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>📧 ${d.email}</span>` : ''}
      ${d.phone ? `<span>📱 ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>💼 ${d.linkedin}</span>` : ''}
      ${d.github ? `<span>🐙 ${d.github}</span>` : ''}
    </div>
  </div>
</div>
${d.summary ? `<div class="section"><div class="section-title">Summary</div><div class="summary">${d.summary}</div></div>` : ''}
<div class="section">
  <div class="section-title">Skills</div>
  ${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}
</div>
${d.experience.length ? `<div class="section"><div class="section-title">Experience</div>${d.experience.map(e => `<div class="item"><div class="item-title">${e.title}</div><div class="item-sub">${e.company}</div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
${d.education.length ? `<div class="section"><div class="section-title">Education</div>${d.education.map(e => `<div class="item"><div class="item-title">${e.degree}</div><div class="item-sub">${e.school}</div></div>`).join('')}</div>` : ''}
${d.projects.length ? `<div class="section"><div class="section-title">Projects</div>${d.projects.map(p => `<div class="item"><div class="item-title">${p.name}</div><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
${d.extra ? `<div class="section"><div class="section-title">Additional</div><div class="summary">${d.extra}</div></div>` : ''}
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'creative-purple': {
    name: 'Creative Purple',
    preview: '💜',
    desc: 'Bold, designer-style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Poppins',sans-serif; background:#faf5ff; }
  .hero { background:linear-gradient(135deg,#7c3aed 0%,#4f46e5 50%,#06b6d4 100%); padding:40px 48px; display:flex; align-items:center; gap:32px; }
  .hero img { width:120px; height:120px; border-radius:20px; object-fit:cover; border:4px solid rgba(255,255,255,0.4); box-shadow:0 8px 32px rgba(0,0,0,0.2); }
  .hero-placeholder { width:120px; height:120px; border-radius:20px; background:rgba(255,255,255,0.2); display:flex; align-items:center; justify-content:center; font-size:48px; flex-shrink:0; }
  .hero-info h1 { font-size:36px; font-weight:800; color:#fff; letter-spacing:-1px; }
  .hero-info .role { font-size:16px; color:rgba(255,255,255,0.8); font-weight:300; margin-top:6px; }
  .hero-contacts { display:flex; gap:16px; margin-top:12px; flex-wrap:wrap; }
  .hero-contacts span { font-size:12px; color:rgba(255,255,255,0.9); background:rgba(255,255,255,0.15); padding:4px 12px; border-radius:20px; }
  .body { display:grid; grid-template-columns:1fr 1.6fr; gap:0; }
  .left { background:#fff; padding:32px 28px; display:flex; flex-direction:column; gap:24px; }
  .right { background:#faf5ff; padding:32px 36px; display:flex; flex-direction:column; gap:24px; }
  .sec-title { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#7c3aed; margin-bottom:12px; display:flex; align-items:center; gap:8px; }
  .sec-title::after { content:''; flex:1; height:2px; background:linear-gradient(90deg,#7c3aed,transparent); }
  .skill-tag { display:inline-block; padding:5px 12px; background:linear-gradient(135deg,#ede9fe,#ddd6fe); color:#5b21b6; border-radius:20px; font-size:11px; margin:3px 2px; font-weight:600; }
  .edu-item { margin-bottom:12px; }
  .edu-degree { font-size:13px; font-weight:600; color:#1e293b; }
  .edu-school { font-size:11px; color:#7c3aed; }
  .item-card { background:#fff; border-radius:12px; padding:14px 16px; margin-bottom:12px; border-left:3px solid #7c3aed; box-shadow:0 2px 8px rgba(124,58,237,0.08); }
  .item-title { font-size:14px; font-weight:700; color:#1e293b; }
  .item-sub { font-size:11px; color:#7c3aed; font-weight:600; margin-top:2px; }
  .item-text { font-size:12px; color:#64748b; line-height:1.7; margin-top:6px; }
  .summary-box { background:linear-gradient(135deg,#ede9fe,#e0e7ff); border-radius:12px; padding:16px; font-size:13px; color:#4c1d95; line-height:1.8; font-style:italic; }
  .footer { background:linear-gradient(135deg,#7c3aed,#4f46e5); color:rgba(255,255,255,0.7); text-align:center; padding:12px; font-size:10px; }
</style>
</head>
<body>
<div class="hero">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="hero-placeholder">👤</div>`}
  <div class="hero-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="hero-contacts">
      ${d.email ? `<span>📧 ${d.email}</span>` : ''}
      ${d.phone ? `<span>📱 ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>💼 ${d.linkedin}</span>` : ''}
      ${d.github ? `<span>🐙 ${d.github}</span>` : ''}
    </div>
  </div>
</div>
<div class="body">
  <div class="left">
    <div><div class="sec-title">Skills</div>${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}</div>
    <div><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div><div class="sec-title">Additional</div><div style="font-size:12px;color:#64748b;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="right">
    ${d.summary ? `<div><div class="sec-title">Summary</div><div class="summary-box">${d.summary}</div></div>` : ''}
    ${d.experience.length ? `<div><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="item-card"><div class="item-title">${e.title}</div><div class="item-sub">${e.company}</div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">Projects</div>${d.projects.map(p => `<div class="item-card"><div class="item-title">${p.name}</div><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'corporate-navy': {
    name: 'Corporate Navy',
    preview: '🏢',
    desc: 'Formal, executive style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&family=Source+Sans+3:wght@400;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Source Sans 3',sans-serif; background:#fff; }
  .header { background:#1e3a5f; padding:36px 48px; display:flex; align-items:center; gap:28px; }
  .header img { width:100px; height:100px; border-radius:8px; object-fit:cover; border:3px solid #c9a84c; }
  .header-ph { width:100px; height:100px; border-radius:8px; background:rgba(255,255,255,0.1); display:flex; align-items:center; justify-content:center; font-size:40px; }
  .header-info h1 { font-family:'Merriweather',serif; font-size:28px; color:#fff; font-weight:700; }
  .header-info .role { font-size:15px; color:#c9a84c; margin-top:6px; font-weight:600; letter-spacing:1px; text-transform:uppercase; }
  .header-info .contacts { display:flex; gap:20px; margin-top:12px; flex-wrap:wrap; }
  .header-info .contacts span { font-size:12px; color:rgba(255,255,255,0.8); }
  .gold-bar { height:4px; background:linear-gradient(90deg,#c9a84c,#e8d08a,#c9a84c); }
  .body { display:grid; grid-template-columns:240px 1fr; }
  .sidebar { background:#f0f4f8; padding:28px 20px; border-right:1px solid #e2e8f0; }
  .main { padding:28px 36px; }
  .sec-title { font-family:'Merriweather',serif; font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#1e3a5f; border-bottom:2px solid #c9a84c; padding-bottom:6px; margin-bottom:12px; }
  .skill-item { font-size:12px; color:#4a5568; padding:5px 0; border-bottom:1px dotted #cbd5e0; display:flex; align-items:center; gap:6px; }
  .skill-item::before { content:'▪'; color:#c9a84c; }
  .edu-item { margin-bottom:14px; }
  .edu-degree { font-size:13px; font-weight:600; color:#2d3748; }
  .edu-school { font-size:11px; color:#718096; }
  .exp-item { margin-bottom:18px; padding-bottom:18px; border-bottom:1px solid #e2e8f0; }
  .exp-item:last-child { border-bottom:none; }
  .exp-title { font-size:15px; font-weight:700; color:#1e3a5f; }
  .exp-company { font-size:12px; color:#c9a84c; font-weight:600; margin-top:2px; }
  .exp-text { font-size:12px; color:#4a5568; line-height:1.8; margin-top:6px; }
  .summary-text { font-size:13px; color:#4a5568; line-height:1.9; padding:14px; background:#f7fafc; border-left:3px solid #1e3a5f; border-radius:0 6px 6px 0; margin-bottom:20px; }
  .footer { background:#1e3a5f; color:rgba(255,255,255,0.6); text-align:center; padding:10px; font-size:10px; }
</style>
</head>
<body>
<div class="header">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="header-ph">👤</div>`}
  <div class="header-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>✉ ${d.email}</span>` : ''}
      ${d.phone ? `<span>☎ ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>🔗 ${d.linkedin}</span>` : ''}
    </div>
  </div>
</div>
<div class="gold-bar"></div>
<div class="body">
  <div class="sidebar">
    <div style="margin-bottom:24px;"><div class="sec-title">Skills</div>${d.skills.map(s => `<div class="skill-item">${s}</div>`).join('')}</div>
    <div><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div style="margin-top:24px;"><div class="sec-title">Other</div><div style="font-size:12px;color:#4a5568;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="main">
    ${d.summary ? `<div class="summary-text">${d.summary}</div>` : ''}
    ${d.experience.length ? `<div style="margin-bottom:24px;"><div class="sec-title">Professional Experience</div>${d.experience.map(e => `<div class="exp-item"><div class="exp-title">${e.title}</div><div class="exp-company">${e.company}</div><div class="exp-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">Key Projects</div>${d.projects.map(p => `<div class="exp-item"><div class="exp-title">${p.name}</div><div class="exp-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'tech-dark': {
    name: 'Tech Dark',
    preview: '💻',
    desc: 'Developer / terminal style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;600;700&family=Inter:wght@400;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',sans-serif; background:#0d1117; color:#c9d1d9; }
  .topbar { background:#161b22; border-bottom:1px solid #30363d; padding:20px 40px; display:flex; align-items:center; gap:20px; }
  .topbar img { width:80px; height:80px; border-radius:50%; object-fit:cover; border:2px solid #238636; }
  .topbar-ph { width:80px; height:80px; border-radius:50%; background:#21262d; display:flex; align-items:center; justify-content:center; font-size:32px; border:2px solid #238636; }
  .topbar-info h1 { font-family:'JetBrains Mono',monospace; font-size:24px; font-weight:700; color:#58a6ff; }
  .topbar-info .role { font-size:13px; color:#7ee787; margin-top:4px; font-family:'JetBrains Mono',monospace; }
  .topbar-info .role::before { content:'> '; color:#f0883e; }
  .contacts { display:flex; gap:16px; margin-top:8px; flex-wrap:wrap; }
  .contacts span { font-size:11px; color:#8b949e; font-family:'JetBrains Mono',monospace; }
  .body { display:grid; grid-template-columns:260px 1fr; min-height:calc(100vh - 120px); }
  .sidebar { background:#161b22; border-right:1px solid #30363d; padding:24px 20px; }
  .main { padding:24px 32px; }
  .sec-title { font-family:'JetBrains Mono',monospace; font-size:11px; font-weight:700; color:#f0883e; margin-bottom:12px; }
  .sec-title::before { content:'# '; }
  .skill-tag { display:inline-block; padding:3px 8px; background:#21262d; border:1px solid #30363d; color:#7ee787; border-radius:4px; font-size:10px; margin:2px; font-family:'JetBrains Mono',monospace; }
  .edu-item { margin-bottom:12px; padding:10px; background:#21262d; border-radius:6px; border-left:2px solid #58a6ff; }
  .edu-degree { font-size:12px; font-weight:600; color:#c9d1d9; }
  .edu-school { font-size:11px; color:#8b949e; margin-top:2px; }
  .card { background:#161b22; border:1px solid #30363d; border-radius:8px; padding:14px 16px; margin-bottom:12px; transition:border-color 0.2s; }
  .card:hover { border-color:#58a6ff; }
  .card-title { font-size:14px; font-weight:600; color:#58a6ff; font-family:'JetBrains Mono',monospace; }
  .card-sub { font-size:11px; color:#7ee787; margin-top:3px; }
  .card-text { font-size:12px; color:#8b949e; line-height:1.7; margin-top:8px; }
  .summary-box { background:#21262d; border:1px solid #30363d; border-radius:8px; padding:16px; margin-bottom:20px; font-size:13px; color:#8b949e; line-height:1.8; border-left:3px solid #f0883e; }
  .footer { background:#161b22; border-top:1px solid #30363d; color:#4d5566; text-align:center; padding:10px; font-size:10px; font-family:'JetBrains Mono',monospace; }
</style>
</head>
<body>
<div class="topbar">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="topbar-ph">👤</div>`}
  <div class="topbar-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>${d.email}</span>` : ''}
      ${d.phone ? `<span>${d.phone}</span>` : ''}
      ${d.github ? `<span>${d.github}</span>` : ''}
      ${d.linkedin ? `<span>${d.linkedin}</span>` : ''}
    </div>
  </div>
</div>
<div class="body">
  <div class="sidebar">
    <div style="margin-bottom:20px;"><div class="sec-title">skills</div>${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}</div>
    <div><div class="sec-title">education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div style="margin-top:20px;"><div class="sec-title">other</div><div style="font-size:12px;color:#8b949e;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="main">
    ${d.summary ? `<div class="summary-box">${d.summary}</div>` : ''}
    ${d.experience.length ? `<div style="margin-bottom:20px;"><div class="sec-title">experience</div>${d.experience.map(e => `<div class="card"><div class="card-title">${e.title}</div><div class="card-sub">${e.company}</div><div class="card-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">projects</div>${d.projects.map(p => `<div class="card"><div class="card-title">${p.name}</div><div class="card-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ generated by hireiq ai studio // arun kumar</div>
</body></html>`
  },
};

// Parse resume text into structured data using AI
export const parseResumeData = async (text, generateFieldContent) => {
  const prompt = `Extract resume information from this text and return ONLY a valid JSON object.

Resume Text:
${text}

Return this exact JSON structure (fill with extracted data, empty arrays if not found):
{
  "name": "Full Name",
  "role": "Job Title/Role",
  "email": "email@example.com",
  "phone": "+91-XXXXX-XXXXX",
  "linkedin": "",
  "github": "",
  "summary": "Professional summary paragraph",
  "skills": ["Skill1", "Skill2", "Skill3"],
  "experience": [
    {"title": "Job Title", "company": "Company Name", "description": "What they did"}
  ],
  "education": [
    {"degree": "Degree Name", "school": "University, Year, CGPA"}
  ],
  "projects": [
    {"name": "Project Name", "description": "What it does"}
  ],
  "extra": "Any other info like certifications, languages, hobbies"
}

IMPORTANT: Return ONLY the JSON object, no markdown, no explanation.`;

  const res = await generateFieldContent(prompt);
  let raw = res.data.result?.trim() || '{}';
  raw = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```$/i, '').trim();

  try {
    return JSON.parse(raw);
  } catch {
    return {
      name: 'Name Not Found', role: 'Role', email: '', phone: '',
      linkedin: '', github: '', summary: text.substring(0, 200),
      skills: [], experience: [], education: [], projects: [], extra: ''
    };
  }
};