import React, { useState } from 'react';
import { FileEdit, Zap, Download, Eye, User, Briefcase, Code, GraduationCap, FolderOpen, Mail, Phone } from 'lucide-react';
import axios from 'axios';

function ResumeBuilder() {
  const [form, setForm] = useState({
    name: '', role: '', experience: '',
    skills: '', education: '', projects: '',
    email: '', phone: '',
  });
  const [loading, setLoading] = useState(false);
  const [htmlPreview, setHtmlPreview] = useState('');
  const [generated, setGenerated] = useState(false);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await axios.post('http://127.0.0.1:5000/ml/build-resume', {
        ...form, format: 'html'
      });
      setHtmlPreview(res.data.html);
      setGenerated(true);
    } catch (err) {
      // Flask offline — demo HTML generate karo
      setHtmlPreview(generateDemoHtml(form));
      setGenerated(true);
    } finally {
      setLoading(false);
    }
  };

  const generateDemoHtml = (data) => `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Segoe UI', sans-serif; color: #333; }
  .header { background: linear-gradient(135deg, #1a1a2e, #16213e);
            color: white; padding: 30px 40px; }
  .name { font-size: 32px; font-weight: 700; letter-spacing: 2px; }
  .role { font-size: 16px; color: #a8b2d8; margin-top: 6px; }
  .contact { margin-top: 10px; font-size: 13px; color: #8892b0; }
  .contact span { margin-right: 20px; }
  .body { display: flex; }
  .sidebar { width: 32%; background: #f8f9fa; padding: 25px 20px; }
  .main { width: 68%; padding: 25px 30px; }
  .section-title { font-size: 13px; font-weight: 700;
                   text-transform: uppercase; letter-spacing: 2px;
                   color: #1a1a2e; border-bottom: 2px solid #1a1a2e;
                   padding-bottom: 5px; margin-bottom: 12px; margin-top: 20px; }
  .section-title:first-child { margin-top: 0; }
  .skill-tag { display: inline-block; background: #EBF5FB;
               color: #1a1a2e; padding: 4px 12px; border-radius: 15px;
               margin: 3px 2px; font-size: 12px; }
  ul { padding-left: 18px; }
  li { margin-bottom: 5px; font-size: 13px; line-height: 1.5; }
  .footer { text-align: center; padding: 10px; font-size: 10px;
            color: #bbb; border-top: 1px solid #eee; }
</style>
</head>
<body>
<div class="header">
  <div class="name">${data.name.toUpperCase()}</div>
  <div class="role">${data.role}</div>
  <div class="contact">
    <span>📧 ${data.email || 'email@example.com'}</span>
    <span>📱 ${data.phone || '+91-XXXXX-XXXXX'}</span>
  </div>
</div>
<div class="body">
  <div class="sidebar">
    <div class="section-title">Skills</div>
    ${data.skills.split(',').map(s =>
      `<span class="skill-tag">${s.trim()}</span>`
    ).join('')}
    <div class="section-title">Education</div>
    <p style="font-size:13px;">${data.education}</p>
  </div>
  <div class="main">
    <div class="section-title">Experience</div>
    <p style="font-size:13px; color:#555;">${data.experience}</p>
    <div class="section-title">Projects</div>
    <p style="font-size:13px; color:#555;">${data.projects}</p>
  </div>
</div>
<div class="footer">⚡ Generated by HireIQ — AI Resume Suite by Arun Kumar</div>
</body>
</html>`;

  const handleDownload = () => {
    const blob = new Blob([htmlPreview], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${form.name.replace(' ', '_')}_Resume.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const inputStyle = {
    width: '100%', padding: '10px 14px',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border-bright)',
    borderRadius: '8px', color: 'var(--text-primary)',
    fontSize: '14px', outline: 'none',
    fontFamily: 'DM Sans, sans-serif',
    boxSizing: 'border-box', transition: 'border-color 0.2s',
  };

  const labelStyle = {
    display: 'flex', alignItems: 'center', gap: '6px',
    fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '8px',
  };

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{
          fontFamily: 'Syne, sans-serif',
          fontSize: '24px', fontWeight: '800', marginBottom: '4px',
        }}>Resume Builder</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>
          AI-powered professional resume generation
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>

        {/* Form */}
        <div className="card" style={{ borderColor: 'var(--accent-green)' }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: '10px',
            marginBottom: '20px',
          }}>
            <div style={{
              width: '36px', height: '36px', borderRadius: '10px',
              background: 'var(--gradient-3)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <FileEdit size={18} color="white" />
            </div>
            <h3 style={{
              fontFamily: 'Syne, sans-serif',
              fontSize: '16px', fontWeight: '700',
            }}>Your Details</h3>
          </div>

          <form onSubmit={handleGenerate}>
            {/* Name + Role */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
              <div>
                <label style={labelStyle}><User size={12} />Full Name</label>
                <input
                  type="text" placeholder="Arun Kumar"
                  value={form.name}
                  onChange={e => setForm({ ...form, name: e.target.value })}
                  required style={inputStyle}
                  onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                  onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
                />
              </div>
              <div>
                <label style={labelStyle}><Briefcase size={12} />Job Role</label>
                <input
                  type="text" placeholder="Python Developer"
                  value={form.role}
                  onChange={e => setForm({ ...form, role: e.target.value })}
                  required style={inputStyle}
                  onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                  onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
                />
              </div>
            </div>

            {/* Email + Phone */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
              <div>
                <label style={labelStyle}><Mail size={12} />Email</label>
                <input
                  type="email" placeholder="arun@email.com"
                  value={form.email}
                  onChange={e => setForm({ ...form, email: e.target.value })}
                  style={inputStyle}
                  onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                  onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
                />
              </div>
              <div>
                <label style={labelStyle}><Phone size={12} />Phone</label>
                <input
                  type="text" placeholder="+91-98XXX-XXXXX"
                  value={form.phone}
                  onChange={e => setForm({ ...form, phone: e.target.value })}
                  style={inputStyle}
                  onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                  onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
                />
              </div>
            </div>

            {/* Experience */}
            <div style={{ marginBottom: '12px' }}>
              <label style={labelStyle}><Briefcase size={12} />Experience</label>
              <textarea
                placeholder="2 years at HCLTech — Python, Django, Microsoft Fabric..."
                value={form.experience}
                onChange={e => setForm({ ...form, experience: e.target.value })}
                rows={3} style={{ ...inputStyle, resize: 'vertical' }}
                onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
              />
            </div>

            {/* Skills */}
            <div style={{ marginBottom: '12px' }}>
              <label style={labelStyle}><Code size={12} />Skills (comma separated)</label>
              <input
                type="text" placeholder="Python, Django, SQL, REST APIs, Git, Docker"
                value={form.skills}
                onChange={e => setForm({ ...form, skills: e.target.value })}
                required style={inputStyle}
                onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
              />
            </div>

            {/* Education */}
            <div style={{ marginBottom: '12px' }}>
              <label style={labelStyle}><GraduationCap size={12} />Education</label>
              <input
                type="text" placeholder="B.Tech CS — NIT Patna 2024, CGPA 8.5"
                value={form.education}
                onChange={e => setForm({ ...form, education: e.target.value })}
                style={inputStyle}
                onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
              />
            </div>

            {/* Projects */}
            <div style={{ marginBottom: '20px' }}>
              <label style={labelStyle}><FolderOpen size={12} />Projects</label>
              <textarea
                placeholder="HireIQ AI Resume Suite — React, .NET, Python, ML..."
                value={form.projects}
                onChange={e => setForm({ ...form, projects: e.target.value })}
                rows={3} style={{ ...inputStyle, resize: 'vertical' }}
                onFocus={e => e.target.style.borderColor = 'var(--accent-green)'}
                onBlur={e => e.target.style.borderColor = 'var(--border-bright)'}
              />
            </div>

            <button
              type="submit"
              className="btn-primary"
              disabled={loading}
              style={{
                width: '100%', justifyContent: 'center',
                padding: '14px',
                background: 'var(--gradient-3)',
              }}
            >
              {loading ? 'Generating...' : (
                <><Zap size={16} /> Generate Resume</>
              )}
            </button>
          </form>
        </div>

        {/* Preview */}
        <div className="card" style={{ padding: '0', overflow: 'hidden' }}>
          <div style={{
            padding: '16px 20px',
            borderBottom: '1px solid var(--border)',
            display: 'flex', alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Eye size={16} color="var(--accent-green)" />
              <span style={{
                fontFamily: 'Syne, sans-serif',
                fontSize: '14px', fontWeight: '700',
              }}>Preview</span>
            </div>
            {generated && (
              <button
                onClick={handleDownload}
                className="btn-primary"
                style={{
                  padding: '8px 16px', fontSize: '13px',
                  background: 'var(--gradient-3)',
                }}
              >
                <Download size={14} /> Download HTML
              </button>
            )}
          </div>

          {!generated ? (
            <div style={{
              display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'center',
              height: '500px', color: 'var(--text-muted)',
            }}>
              <FileEdit size={48} style={{ marginBottom: '12px', opacity: 0.2 }} />
              <p style={{ fontSize: '14px' }}>Fill the form and click Generate!</p>
            </div>
          ) : (
            <iframe
              srcDoc={htmlPreview}
              style={{
                width: '100%', height: '600px',
                border: 'none', background: 'white',
              }}
              title="Resume Preview"
            />
          )}
        </div>
      </div>
    </div>
  );
}

export default ResumeBuilder;
