// src/templates/resumeTemplates.js

export const TEMPLATES = {
  'modern-dark': {
    name: 'Modern Dark',
    preview: '🌑',
    desc: 'Dark sidebar, gradient header',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',sans-serif; display:flex; min-height:100vh; background:#0f0f0f; }
  .sidebar { width:300px; background:linear-gradient(180deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%); padding:32px 24px; display:flex; flex-direction:column; gap:24px; }
  .photo-wrap { text-align:center; }
  .photo-wrap img { width:110px; height:110px; border-radius:50%; object-fit:cover; border:3px solid #7c3aed; }
  .photo-placeholder { width:110px; height:110px; border-radius:50%; background:rgba(124,58,237,0.3); display:flex; align-items:center; justify-content:center; margin:0 auto; font-size:36px; }
  .name { font-size:22px; font-weight:800; color:#fff; text-align:center; margin-top:12px; }
  .role { font-size:13px; color:#a78bfa; text-align:center; margin-top:4px; font-weight:500; }
  .divider { height:1px; background:rgba(255,255,255,0.1); }
  .section-title { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#7c3aed; margin-bottom:10px; }
  .contact-item { font-size:12px; color:#cbd5e1; margin-bottom:6px; display:flex; align-items:center; gap:8px; }
  .skill-tag { display:inline-block; padding:4px 10px; background:rgba(124,58,237,0.3); color:#a78bfa; border-radius:12px; font-size:11px; margin:3px 2px; border:1px solid rgba(124,58,237,0.4); }
  .edu-item { margin-bottom:10px; }
  .edu-degree { font-size:12px; font-weight:600; color:#e2e8f0; }
  .edu-school { font-size:11px; color:#94a3b8; }
  .main { flex:1; background:#f8fafc; padding:40px 36px; }
  .summary-box { background:linear-gradient(135deg,#ede9fe,#ddd6fe); border-left:4px solid #7c3aed; padding:16px 20px; border-radius:0 12px 12px 0; margin-bottom:28px; }
  .summary-box p { font-size:13px; color:#4c1d95; line-height:1.8; font-style:italic; }
  .main-section { margin-bottom:28px; }
  .main-title { font-size:14px; font-weight:800; color:#1e293b; text-transform:uppercase; letter-spacing:1.5px; border-bottom:2px solid #7c3aed; padding-bottom:6px; margin-bottom:14px; }
  .exp-item { margin-bottom:14px; }
  .exp-role { font-size:14px; font-weight:700; color:#1e293b; }
  .exp-company { font-size:12px; color:#7c3aed; font-weight:600; }
  .exp-text { font-size:12px; color:#475569; line-height:1.7; margin-top:4px; }
  ul.bullets { padding-left:16px; }
  ul.bullets li { font-size:12px; color:#475569; line-height:1.7; margin-bottom:4px; }
  .footer { background:#1a1a2e; color:#94a3b8; text-align:center; padding:10px; font-size:10px; }
</style>
</head>
<body>
<div style="display:flex;flex-direction:column;width:100%;">
<div style="display:flex;flex:1;">
<div class="sidebar">
  <div class="photo-wrap">
    ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="photo-placeholder">👤</div>`}
    <div class="name">${d.name}</div>
    <div class="role">${d.role}</div>
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Contact</div>
    ${d.email ? `<div class="contact-item">📧 ${d.email}</div>` : ''}
    ${d.phone ? `<div class="contact-item">📱 ${d.phone}</div>` : ''}
    ${d.linkedin ? `<div class="contact-item">💼 ${d.linkedin}</div>` : ''}
    ${d.github ? `<div class="contact-item">🐙 ${d.github}</div>` : ''}
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Skills</div>
    ${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}
  </div>
  <div class="divider"></div>
  <div>
    <div class="section-title">Education</div>
    ${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}
  </div>
</div>
<div class="main">
  ${d.summary ? `<div class="summary-box"><p>${d.summary}</p></div>` : ''}
  ${d.experience.length ? `
  <div class="main-section">
    <div class="main-title">Experience</div>
    ${d.experience.map(e => `<div class="exp-item"><div class="exp-role">${e.title}</div><div class="exp-company">${e.company}</div><div class="exp-text">${e.description}</div></div>`).join('')}
  </div>` : ''}
  ${d.projects.length ? `
  <div class="main-section">
    <div class="main-title">Projects</div>
    ${d.projects.map(p => `<div class="exp-item"><div class="exp-role">${p.name}</div><div class="exp-text">${p.description}</div></div>`).join('')}
  </div>` : ''}
  ${d.extra ? `<div class="main-section"><div class="main-title">Additional</div><div class="exp-text">${d.extra}</div></div>` : ''}
</div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</div>
</body></html>`
  },

  'minimal-white': {
    name: 'Minimal White',
    preview: '⬜',
    desc: 'Clean, ATS-friendly',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Lato',sans-serif; background:#fff; color:#2d3748; max-width:860px; margin:0 auto; padding:48px 52px; }
  .header { border-bottom:3px solid #2d3748; padding-bottom:20px; margin-bottom:28px; display:flex; align-items:center; gap:24px; }
  .header img { width:90px; height:90px; border-radius:50%; object-fit:cover; }
  .header-text h1 { font-size:32px; font-weight:900; color:#1a202c; letter-spacing:-0.5px; }
  .header-text .role { font-size:16px; color:#718096; font-weight:300; margin-top:4px; }
  .header-text .contacts { display:flex; gap:16px; margin-top:8px; flex-wrap:wrap; }
  .header-text .contacts span { font-size:12px; color:#4a5568; }
  .section { margin-bottom:24px; }
  .section-title { font-size:11px; font-weight:900; text-transform:uppercase; letter-spacing:3px; color:#718096; margin-bottom:12px; }
  .summary { font-size:13px; line-height:1.8; color:#4a5568; }
  .skill-tag { display:inline-block; padding:3px 10px; border:1px solid #cbd5e0; border-radius:4px; font-size:12px; color:#4a5568; margin:3px 2px; }
  .item { margin-bottom:14px; padding-bottom:14px; border-bottom:1px solid #edf2f7; }
  .item:last-child { border-bottom:none; }
  .item-title { font-size:14px; font-weight:700; color:#2d3748; }
  .item-sub { font-size:12px; color:#718096; margin-top:2px; }
  .item-text { font-size:12px; color:#4a5568; line-height:1.7; margin-top:6px; }
  .footer { border-top:1px solid #e2e8f0; margin-top:32px; padding-top:10px; text-align:center; font-size:10px; color:#a0aec0; }
</style>
</head>
<body>
<div class="header">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : ''}
  <div class="header-text">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>📧 ${d.email}</span>` : ''}
      ${d.phone ? `<span>📱 ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>💼 ${d.linkedin}</span>` : ''}
      ${d.github ? `<span>🐙 ${d.github}</span>` : ''}
    </div>
  </div>
</div>
${d.summary ? `<div class="section"><div class="section-title">Summary</div><div class="summary">${d.summary}</div></div>` : ''}
<div class="section">
  <div class="section-title">Skills</div>
  ${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}
</div>
${d.experience.length ? `<div class="section"><div class="section-title">Experience</div>${d.experience.map(e => `<div class="item"><div class="item-title">${e.title}</div><div class="item-sub">${e.company}</div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
${d.education.length ? `<div class="section"><div class="section-title">Education</div>${d.education.map(e => `<div class="item"><div class="item-title">${e.degree}</div><div class="item-sub">${e.school}</div></div>`).join('')}</div>` : ''}
${d.projects.length ? `<div class="section"><div class="section-title">Projects</div>${d.projects.map(p => `<div class="item"><div class="item-title">${p.name}</div><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
${d.extra ? `<div class="section"><div class="section-title">Additional</div><div class="summary">${d.extra}</div></div>` : ''}
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'creative-purple': {
    name: 'Creative Purple',
    preview: '💜',
    desc: 'Bold, designer-style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Poppins',sans-serif; background:#faf5ff; }
  .hero { background:linear-gradient(135deg,#7c3aed 0%,#4f46e5 50%,#06b6d4 100%); padding:40px 48px; display:flex; align-items:center; gap:32px; }
  .hero img { width:120px; height:120px; border-radius:20px; object-fit:cover; border:4px solid rgba(255,255,255,0.4); box-shadow:0 8px 32px rgba(0,0,0,0.2); }
  .hero-placeholder { width:120px; height:120px; border-radius:20px; background:rgba(255,255,255,0.2); display:flex; align-items:center; justify-content:center; font-size:48px; flex-shrink:0; }
  .hero-info h1 { font-size:36px; font-weight:800; color:#fff; letter-spacing:-1px; }
  .hero-info .role { font-size:16px; color:rgba(255,255,255,0.8); font-weight:300; margin-top:6px; }
  .hero-contacts { display:flex; gap:16px; margin-top:12px; flex-wrap:wrap; }
  .hero-contacts span { font-size:12px; color:rgba(255,255,255,0.9); background:rgba(255,255,255,0.15); padding:4px 12px; border-radius:20px; }
  .body { display:grid; grid-template-columns:1fr 1.6fr; gap:0; }
  .left { background:#fff; padding:32px 28px; display:flex; flex-direction:column; gap:24px; }
  .right { background:#faf5ff; padding:32px 36px; display:flex; flex-direction:column; gap:24px; }
  .sec-title { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#7c3aed; margin-bottom:12px; display:flex; align-items:center; gap:8px; }
  .sec-title::after { content:''; flex:1; height:2px; background:linear-gradient(90deg,#7c3aed,transparent); }
  .skill-tag { display:inline-block; padding:5px 12px; background:linear-gradient(135deg,#ede9fe,#ddd6fe); color:#5b21b6; border-radius:20px; font-size:11px; margin:3px 2px; font-weight:600; }
  .edu-item { margin-bottom:12px; }
  .edu-degree { font-size:13px; font-weight:600; color:#1e293b; }
  .edu-school { font-size:11px; color:#7c3aed; }
  .item-card { background:#fff; border-radius:12px; padding:14px 16px; margin-bottom:12px; border-left:3px solid #7c3aed; box-shadow:0 2px 8px rgba(124,58,237,0.08); }
  .item-title { font-size:14px; font-weight:700; color:#1e293b; }
  .item-sub { font-size:11px; color:#7c3aed; font-weight:600; margin-top:2px; }
  .item-text { font-size:12px; color:#64748b; line-height:1.7; margin-top:6px; }
  .summary-box { background:linear-gradient(135deg,#ede9fe,#e0e7ff); border-radius:12px; padding:16px; font-size:13px; color:#4c1d95; line-height:1.8; font-style:italic; }
  .footer { background:linear-gradient(135deg,#7c3aed,#4f46e5); color:rgba(255,255,255,0.7); text-align:center; padding:12px; font-size:10px; }
</style>
</head>
<body>
<div class="hero">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="hero-placeholder">👤</div>`}
  <div class="hero-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="hero-contacts">
      ${d.email ? `<span>📧 ${d.email}</span>` : ''}
      ${d.phone ? `<span>📱 ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>💼 ${d.linkedin}</span>` : ''}
      ${d.github ? `<span>🐙 ${d.github}</span>` : ''}
    </div>
  </div>
</div>
<div class="body">
  <div class="left">
    <div><div class="sec-title">Skills</div>${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}</div>
    <div><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div><div class="sec-title">Additional</div><div style="font-size:12px;color:#64748b;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="right">
    ${d.summary ? `<div><div class="sec-title">Summary</div><div class="summary-box">${d.summary}</div></div>` : ''}
    ${d.experience.length ? `<div><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="item-card"><div class="item-title">${e.title}</div><div class="item-sub">${e.company}</div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">Projects</div>${d.projects.map(p => `<div class="item-card"><div class="item-title">${p.name}</div><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'corporate-navy': {
    name: 'Corporate Navy',
    preview: '🏢',
    desc: 'Formal, executive style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&family=Source+Sans+3:wght@400;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Source Sans 3',sans-serif; background:#fff; }
  .header { background:#1e3a5f; padding:36px 48px; display:flex; align-items:center; gap:28px; }
  .header img { width:100px; height:100px; border-radius:8px; object-fit:cover; border:3px solid #c9a84c; }
  .header-ph { width:100px; height:100px; border-radius:8px; background:rgba(255,255,255,0.1); display:flex; align-items:center; justify-content:center; font-size:40px; }
  .header-info h1 { font-family:'Merriweather',serif; font-size:28px; color:#fff; font-weight:700; }
  .header-info .role { font-size:15px; color:#c9a84c; margin-top:6px; font-weight:600; letter-spacing:1px; text-transform:uppercase; }
  .header-info .contacts { display:flex; gap:20px; margin-top:12px; flex-wrap:wrap; }
  .header-info .contacts span { font-size:12px; color:rgba(255,255,255,0.8); }
  .gold-bar { height:4px; background:linear-gradient(90deg,#c9a84c,#e8d08a,#c9a84c); }
  .body { display:grid; grid-template-columns:240px 1fr; }
  .sidebar { background:#f0f4f8; padding:28px 20px; border-right:1px solid #e2e8f0; }
  .main { padding:28px 36px; }
  .sec-title { font-family:'Merriweather',serif; font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#1e3a5f; border-bottom:2px solid #c9a84c; padding-bottom:6px; margin-bottom:12px; }
  .skill-item { font-size:12px; color:#4a5568; padding:5px 0; border-bottom:1px dotted #cbd5e0; display:flex; align-items:center; gap:6px; }
  .skill-item::before { content:'▪'; color:#c9a84c; }
  .edu-item { margin-bottom:14px; }
  .edu-degree { font-size:13px; font-weight:600; color:#2d3748; }
  .edu-school { font-size:11px; color:#718096; }
  .exp-item { margin-bottom:18px; padding-bottom:18px; border-bottom:1px solid #e2e8f0; }
  .exp-item:last-child { border-bottom:none; }
  .exp-title { font-size:15px; font-weight:700; color:#1e3a5f; }
  .exp-company { font-size:12px; color:#c9a84c; font-weight:600; margin-top:2px; }
  .exp-text { font-size:12px; color:#4a5568; line-height:1.8; margin-top:6px; }
  .summary-text { font-size:13px; color:#4a5568; line-height:1.9; padding:14px; background:#f7fafc; border-left:3px solid #1e3a5f; border-radius:0 6px 6px 0; margin-bottom:20px; }
  .footer { background:#1e3a5f; color:rgba(255,255,255,0.6); text-align:center; padding:10px; font-size:10px; }
</style>
</head>
<body>
<div class="header">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="header-ph">👤</div>`}
  <div class="header-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>✉ ${d.email}</span>` : ''}
      ${d.phone ? `<span>☎ ${d.phone}</span>` : ''}
      ${d.linkedin ? `<span>🔗 ${d.linkedin}</span>` : ''}
    </div>
  </div>
</div>
<div class="gold-bar"></div>
<div class="body">
  <div class="sidebar">
    <div style="margin-bottom:24px;"><div class="sec-title">Skills</div>${d.skills.map(s => `<div class="skill-item">${s}</div>`).join('')}</div>
    <div><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div style="margin-top:24px;"><div class="sec-title">Other</div><div style="font-size:12px;color:#4a5568;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="main">
    ${d.summary ? `<div class="summary-text">${d.summary}</div>` : ''}
    ${d.experience.length ? `<div style="margin-bottom:24px;"><div class="sec-title">Professional Experience</div>${d.experience.map(e => `<div class="exp-item"><div class="exp-title">${e.title}</div><div class="exp-company">${e.company}</div><div class="exp-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">Key Projects</div>${d.projects.map(p => `<div class="exp-item"><div class="exp-title">${p.name}</div><div class="exp-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ Generated by HireIQ AI Studio by Arun Kumar</div>
</body></html>`
  },

  'tech-dark': {
    name: 'Tech Dark',
    preview: '💻',
    desc: 'Developer / terminal style',
    render: (d) => `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;600;700&family=Inter:wght@400;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',sans-serif; background:#0d1117; color:#c9d1d9; }
  .topbar { background:#161b22; border-bottom:1px solid #30363d; padding:20px 40px; display:flex; align-items:center; gap:20px; }
  .topbar img { width:80px; height:80px; border-radius:50%; object-fit:cover; border:2px solid #238636; }
  .topbar-ph { width:80px; height:80px; border-radius:50%; background:#21262d; display:flex; align-items:center; justify-content:center; font-size:32px; border:2px solid #238636; }
  .topbar-info h1 { font-family:'JetBrains Mono',monospace; font-size:24px; font-weight:700; color:#58a6ff; }
  .topbar-info .role { font-size:13px; color:#7ee787; margin-top:4px; font-family:'JetBrains Mono',monospace; }
  .topbar-info .role::before { content:'> '; color:#f0883e; }
  .contacts { display:flex; gap:16px; margin-top:8px; flex-wrap:wrap; }
  .contacts span { font-size:11px; color:#8b949e; font-family:'JetBrains Mono',monospace; }
  .body { display:grid; grid-template-columns:260px 1fr; min-height:calc(100vh - 120px); }
  .sidebar { background:#161b22; border-right:1px solid #30363d; padding:24px 20px; }
  .main { padding:24px 32px; }
  .sec-title { font-family:'JetBrains Mono',monospace; font-size:11px; font-weight:700; color:#f0883e; margin-bottom:12px; }
  .sec-title::before { content:'# '; }
  .skill-tag { display:inline-block; padding:3px 8px; background:#21262d; border:1px solid #30363d; color:#7ee787; border-radius:4px; font-size:10px; margin:2px; font-family:'JetBrains Mono',monospace; }
  .edu-item { margin-bottom:12px; padding:10px; background:#21262d; border-radius:6px; border-left:2px solid #58a6ff; }
  .edu-degree { font-size:12px; font-weight:600; color:#c9d1d9; }
  .edu-school { font-size:11px; color:#8b949e; margin-top:2px; }
  .card { background:#161b22; border:1px solid #30363d; border-radius:8px; padding:14px 16px; margin-bottom:12px; transition:border-color 0.2s; }
  .card:hover { border-color:#58a6ff; }
  .card-title { font-size:14px; font-weight:600; color:#58a6ff; font-family:'JetBrains Mono',monospace; }
  .card-sub { font-size:11px; color:#7ee787; margin-top:3px; }
  .card-text { font-size:12px; color:#8b949e; line-height:1.7; margin-top:8px; }
  .summary-box { background:#21262d; border:1px solid #30363d; border-radius:8px; padding:16px; margin-bottom:20px; font-size:13px; color:#8b949e; line-height:1.8; border-left:3px solid #f0883e; }
  .footer { background:#161b22; border-top:1px solid #30363d; color:#4d5566; text-align:center; padding:10px; font-size:10px; font-family:'JetBrains Mono',monospace; }
</style>
</head>
<body>
<div class="topbar">
  ${d.photo ? `<img src="${d.photo}" alt="Profile" />` : `<div class="topbar-ph">👤</div>`}
  <div class="topbar-info">
    <h1>${d.name}</h1>
    <div class="role">${d.role}</div>
    <div class="contacts">
      ${d.email ? `<span>${d.email}</span>` : ''}
      ${d.phone ? `<span>${d.phone}</span>` : ''}
      ${d.github ? `<span>${d.github}</span>` : ''}
      ${d.linkedin ? `<span>${d.linkedin}</span>` : ''}
    </div>
  </div>
</div>
<div class="body">
  <div class="sidebar">
    <div style="margin-bottom:20px;"><div class="sec-title">skills</div>${d.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}</div>
    <div><div class="sec-title">education</div>${d.education.map(e => `<div class="edu-item"><div class="edu-degree">${e.degree}</div><div class="edu-school">${e.school}</div></div>`).join('')}</div>
    ${d.extra ? `<div style="margin-top:20px;"><div class="sec-title">other</div><div style="font-size:12px;color:#8b949e;line-height:1.7;">${d.extra}</div></div>` : ''}
  </div>
  <div class="main">
    ${d.summary ? `<div class="summary-box">${d.summary}</div>` : ''}
    ${d.experience.length ? `<div style="margin-bottom:20px;"><div class="sec-title">experience</div>${d.experience.map(e => `<div class="card"><div class="card-title">${e.title}</div><div class="card-sub">${e.company}</div><div class="card-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects.length ? `<div><div class="sec-title">projects</div>${d.projects.map(p => `<div class="card"><div class="card-title">${p.name}</div><div class="card-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
<div class="footer">⚡ generated by hireiq ai studio // arun kumar</div>
</body></html>`
  },

  // ═══════════════ PREMIUM TEMPLATES ═══════════════

  'executive-serif': {
    name: 'Executive Serif',
    preview: '🏛️',
    desc: 'Classic serif, ivory & gold — senior roles',
    premium: true,
    render: (d) => `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700;900&family=Source+Sans+3:wght@300;400;600&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Source Sans 3',sans-serif; background:#fffdf7; color:#2b2b2b; max-width:860px; margin:0 auto; padding:52px 56px; }
  .header { text-align:center; border-bottom:1px solid #c9a84c; padding-bottom:24px; margin-bottom:30px; }
  .header h1 { font-family:'Playfair Display',serif; font-size:34px; font-weight:900; color:#1a1a1a; letter-spacing:1px; }
  .header .role { font-size:14px; color:#c9a84c; text-transform:uppercase; letter-spacing:4px; margin-top:8px; font-weight:600; }
  .header .contacts { margin-top:12px; font-size:12px; color:#666; }
  .header .contacts span { margin:0 10px; }
  .sec { margin-bottom:26px; }
  .sec-title { font-family:'Playfair Display',serif; font-size:16px; font-weight:700; color:#1a1a1a; margin-bottom:12px; position:relative; padding-bottom:6px; }
  .sec-title:after { content:''; position:absolute; bottom:0; left:0; width:36px; height:2px; background:#c9a84c; }
  .summary { font-size:13px; line-height:1.9; color:#444; font-style:italic; }
  .item { margin-bottom:14px; }
  .item-head { display:flex; justify-content:space-between; align-items:baseline; }
  .item-title { font-size:14px; font-weight:600; color:#1a1a1a; }
  .item-sub { font-size:12px; color:#c9a84c; font-weight:600; }
  .item-text { font-size:12.5px; color:#555; line-height:1.8; margin-top:4px; }
  .skills { display:flex; flex-wrap:wrap; gap:0; }
  .skills span { font-size:12px; color:#444; }
  .skills span:not(:last-child):after { content:'·'; margin:0 8px; color:#c9a84c; }
  .two-col { display:flex; gap:40px; }
  .two-col > div { flex:1; }
  .footer { text-align:center; font-size:9px; color:#bbb; margin-top:30px; }
</style></head>
<body>
<div class="header">
  <h1>${d.name}</h1>
  <div class="role">${d.role}</div>
  <div class="contacts">
    ${[d.email, d.phone, d.linkedin, d.github].filter(Boolean).map(c => `<span>${c}</span>`).join('')}
  </div>
</div>
${d.summary ? `<div class="sec"><div class="sec-title">Profile</div><p class="summary">${d.summary}</p></div>` : ''}
${d.experience?.length ? `<div class="sec"><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="item"><div class="item-head"><span class="item-title">${e.title}</span><span class="item-sub">${e.company}</span></div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
${d.projects?.length ? `<div class="sec"><div class="sec-title">Selected Projects</div>${d.projects.map(p => `<div class="item"><div class="item-title">${p.name}</div><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
<div class="two-col">
  ${d.skills?.length ? `<div class="sec"><div class="sec-title">Expertise</div><div class="skills">${d.skills.map(s => `<span>${s}</span>`).join('')}</div></div>` : ''}
  ${d.education?.length ? `<div class="sec"><div class="sec-title">Education</div>${d.education.map(e => `<div class="item"><div class="item-title">${e.degree}</div><div class="item-text">${e.school}</div></div>`).join('')}</div>` : ''}
</div>
${d.extra ? `<div class="sec"><div class="sec-title">Additional</div><div class="item-text">${d.extra}</div></div>` : ''}
<div class="footer">Generated by HireIQ AI Studio</div>
</body></html>`
  },

  'slate-sidebar': {
    name: 'Slate Sidebar',
    preview: '🪨',
    desc: 'Light sidebar, teal accents — print-perfect',
    premium: true,
    render: (d) => `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'IBM Plex Sans',sans-serif; display:flex; background:#fff; color:#23323f; min-height:100vh; }
  .side { width:270px; background:#f1f5f7; padding:36px 26px; border-right:3px solid #0d9488; }
  .name { font-size:24px; font-weight:700; line-height:1.2; color:#0f2a33; }
  .role { font-size:13px; color:#0d9488; font-weight:600; margin-top:6px; }
  .blk { margin-top:26px; }
  .blk-title { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:2.5px; color:#0d9488; margin-bottom:10px; }
  .contact { font-size:11.5px; color:#46606e; margin-bottom:6px; word-break:break-all; }
  .skill { display:block; font-size:12px; color:#23323f; padding:5px 0; border-bottom:1px solid #dde7ea; }
  .edu { margin-bottom:10px; }
  .edu b { font-size:12px; color:#0f2a33; display:block; }
  .edu span { font-size:11px; color:#6b8693; }
  .main { flex:1; padding:42px 38px; }
  .m-sec { margin-bottom:26px; }
  .m-title { font-size:13px; font-weight:700; text-transform:uppercase; letter-spacing:2px; color:#0f2a33; border-bottom:2px solid #0d9488; display:inline-block; padding-bottom:4px; margin-bottom:14px; }
  .summary { font-size:13px; line-height:1.8; color:#46606e; }
  .xp { margin-bottom:14px; padding-left:14px; border-left:2px solid #d7e5e3; }
  .xp-title { font-size:14px; font-weight:600; color:#0f2a33; }
  .xp-co { font-size:12px; color:#0d9488; font-weight:600; }
  .xp-text { font-size:12px; color:#46606e; line-height:1.7; margin-top:4px; }
</style></head>
<body>
<div class="side">
  <div class="name">${d.name}</div>
  <div class="role">${d.role}</div>
  <div class="blk"><div class="blk-title">Contact</div>
    ${[d.email, d.phone, d.linkedin, d.github].filter(Boolean).map(c => `<div class="contact">${c}</div>`).join('')}
  </div>
  ${d.skills?.length ? `<div class="blk"><div class="blk-title">Skills</div>${d.skills.map(s => `<span class="skill">${s}</span>`).join('')}</div>` : ''}
  ${d.education?.length ? `<div class="blk"><div class="blk-title">Education</div>${d.education.map(e => `<div class="edu"><b>${e.degree}</b><span>${e.school}</span></div>`).join('')}</div>` : ''}
</div>
<div class="main">
  ${d.summary ? `<div class="m-sec"><div class="m-title">Summary</div><p class="summary">${d.summary}</p></div>` : ''}
  ${d.experience?.length ? `<div class="m-sec"><div class="m-title">Experience</div>${d.experience.map(e => `<div class="xp"><div class="xp-title">${e.title}</div><div class="xp-co">${e.company}</div><div class="xp-text">${e.description}</div></div>`).join('')}</div>` : ''}
  ${d.projects?.length ? `<div class="m-sec"><div class="m-title">Projects</div>${d.projects.map(p => `<div class="xp"><div class="xp-title">${p.name}</div><div class="xp-text">${p.description}</div></div>`).join('')}</div>` : ''}
  ${d.extra ? `<div class="m-sec"><div class="m-title">Additional</div><div class="xp-text" style="border:none;padding:0;">${d.extra}</div></div>` : ''}
</div>
</body></html>`
  },

  'compact-pro': {
    name: 'Compact Pro',
    preview: '📄',
    desc: 'Dense one-pager — maximum ATS compatibility',
    premium: true,
    render: (d) => `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Roboto',sans-serif; background:#fff; color:#212121; max-width:840px; margin:0 auto; padding:36px 44px; font-size:12px; }
  .top { display:flex; justify-content:space-between; align-items:flex-end; border-bottom:2px solid #1565c0; padding-bottom:12px; margin-bottom:16px; }
  h1 { font-size:26px; font-weight:700; color:#0d2c54; }
  .role { font-size:13px; color:#1565c0; font-weight:500; margin-top:2px; }
  .contacts { text-align:right; font-size:11px; color:#555; line-height:1.6; }
  .sec { margin-bottom:14px; }
  .sec-title { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:1.5px; color:#1565c0; margin-bottom:6px; }
  .summary { line-height:1.6; color:#424242; }
  .skills-line { line-height:1.8; color:#424242; }
  .skills-line b { color:#0d2c54; }
  .item { margin-bottom:8px; }
  .item-head { display:flex; justify-content:space-between; }
  .item-title { font-weight:700; color:#212121; font-size:12.5px; }
  .item-co { color:#1565c0; font-weight:500; font-size:11.5px; }
  .item-text { color:#555; line-height:1.55; margin-top:2px; }
</style></head>
<body>
<div class="top">
  <div><h1>${d.name}</h1><div class="role">${d.role}</div></div>
  <div class="contacts">${[d.email, d.phone, d.linkedin, d.github].filter(Boolean).join('<br>')}</div>
</div>
${d.summary ? `<div class="sec"><div class="sec-title">Summary</div><div class="summary">${d.summary}</div></div>` : ''}
${d.skills?.length ? `<div class="sec"><div class="sec-title">Skills</div><div class="skills-line">${d.skills.join(' • ')}</div></div>` : ''}
${d.experience?.length ? `<div class="sec"><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="item"><div class="item-head"><span class="item-title">${e.title}</span><span class="item-co">${e.company}</span></div><div class="item-text">${e.description}</div></div>`).join('')}</div>` : ''}
${d.projects?.length ? `<div class="sec"><div class="sec-title">Projects</div>${d.projects.map(p => `<div class="item"><span class="item-title">${p.name}</span><div class="item-text">${p.description}</div></div>`).join('')}</div>` : ''}
${d.education?.length ? `<div class="sec"><div class="sec-title">Education</div>${d.education.map(e => `<div class="item"><span class="item-title">${e.degree}</span><div class="item-text">${e.school}</div></div>`).join('')}</div>` : ''}
${d.extra ? `<div class="sec"><div class="sec-title">Additional</div><div class="item-text">${d.extra}</div></div>` : ''}
</body></html>`
  },

  'aurora-banner': {
    name: 'Aurora Banner',
    preview: '🌅',
    desc: 'Bold gradient banner, modern & vibrant',
    premium: true,
    render: (d) => `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Outfit',sans-serif; background:#fff; color:#1e1b2e; }
  .banner { background:linear-gradient(120deg,#6d28d9 0%,#db2777 60%,#f59e0b 110%); padding:44px 48px; color:#fff; }
  .banner h1 { font-size:32px; font-weight:800; letter-spacing:-0.5px; }
  .banner .role { font-size:15px; opacity:0.92; font-weight:300; margin-top:4px; }
  .banner .contacts { display:flex; flex-wrap:wrap; gap:18px; margin-top:14px; font-size:12px; opacity:0.95; }
  .wrap { max-width:860px; margin:0 auto; padding:36px 48px; }
  .summary { background:#faf5ff; border:1px solid #e9d5ff; border-radius:12px; padding:16px 20px; font-size:13px; line-height:1.8; color:#4c1d95; margin-bottom:26px; }
  .sec { margin-bottom:26px; }
  .sec-title { font-size:13px; font-weight:800; text-transform:uppercase; letter-spacing:2px; margin-bottom:14px; background:linear-gradient(90deg,#6d28d9,#db2777); -webkit-background-clip:text; background-clip:text; color:transparent; }
  .xp { display:flex; gap:14px; margin-bottom:14px; }
  .dot { width:10px; height:10px; border-radius:50%; background:linear-gradient(120deg,#6d28d9,#db2777); margin-top:5px; flex-shrink:0; }
  .xp-title { font-size:14px; font-weight:600; }
  .xp-co { font-size:12px; color:#db2777; font-weight:600; }
  .xp-text { font-size:12px; color:#57534e; line-height:1.7; margin-top:3px; }
  .tags { display:flex; flex-wrap:wrap; gap:6px; }
  .tag { padding:5px 12px; border-radius:999px; font-size:11.5px; font-weight:600; background:#faf5ff; color:#6d28d9; border:1px solid #e9d5ff; }
  .grid2 { display:flex; gap:36px; }
  .grid2 > div { flex:1; }
  .edu b { display:block; font-size:12.5px; }
  .edu span { font-size:11.5px; color:#78716c; }
  .edu { margin-bottom:10px; }
</style></head>
<body>
<div class="banner">
  <h1>${d.name}</h1>
  <div class="role">${d.role}</div>
  <div class="contacts">${[d.email, d.phone, d.linkedin, d.github].filter(Boolean).map(c => `<span>${c}</span>`).join('')}</div>
</div>
<div class="wrap">
  ${d.summary ? `<div class="summary">${d.summary}</div>` : ''}
  ${d.experience?.length ? `<div class="sec"><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="xp"><div class="dot"></div><div><div class="xp-title">${e.title}</div><div class="xp-co">${e.company}</div><div class="xp-text">${e.description}</div></div></div>`).join('')}</div>` : ''}
  ${d.projects?.length ? `<div class="sec"><div class="sec-title">Projects</div>${d.projects.map(p => `<div class="xp"><div class="dot"></div><div><div class="xp-title">${p.name}</div><div class="xp-text">${p.description}</div></div></div>`).join('')}</div>` : ''}
  <div class="grid2">
    ${d.skills?.length ? `<div class="sec"><div class="sec-title">Skills</div><div class="tags">${d.skills.map(s => `<span class="tag">${s}</span>`).join('')}</div></div>` : ''}
    ${d.education?.length ? `<div class="sec"><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu"><b>${e.degree}</b><span>${e.school}</span></div>`).join('')}</div>` : ''}
  </div>
  ${d.extra ? `<div class="sec"><div class="sec-title">Additional</div><div class="xp-text">${d.extra}</div></div>` : ''}
</div>
</body></html>`
  },

  'swiss-grid': {
    name: 'Swiss Grid',
    preview: '🇨🇭',
    desc: 'International typographic style — bold red',
    premium: true,
    render: (d) => `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700;900&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Archivo',sans-serif; background:#fff; color:#111; max-width:880px; margin:0 auto; padding:48px 50px; }
  .head { display:grid; grid-template-columns:2fr 1fr; gap:24px; border-bottom:6px solid #e11d48; padding-bottom:22px; margin-bottom:28px; }
  h1 { font-size:40px; font-weight:900; letter-spacing:-1.5px; line-height:0.95; text-transform:uppercase; }
  .role { font-size:14px; font-weight:700; color:#e11d48; margin-top:10px; text-transform:uppercase; letter-spacing:1px; }
  .contacts { font-size:11px; line-height:1.9; text-align:right; color:#333; align-self:end; }
  .grid { display:grid; grid-template-columns:1fr 2fr; gap:34px; }
  .sec { margin-bottom:24px; }
  .sec-title { font-size:11px; font-weight:900; text-transform:uppercase; letter-spacing:2px; color:#111; margin-bottom:10px; }
  .sec-title:before { content:'■ '; color:#e11d48; }
  .summary { font-size:12.5px; line-height:1.8; color:#333; }
  .skill { display:block; font-size:12px; font-weight:500; padding:4px 0; border-bottom:1px solid #eee; }
  .edu { margin-bottom:10px; }
  .edu b { font-size:12px; display:block; }
  .edu span { font-size:11px; color:#666; }
  .xp { margin-bottom:16px; }
  .xp-head { display:flex; justify-content:space-between; align-items:baseline; }
  .xp-title { font-size:14px; font-weight:700; }
  .xp-co { font-size:11px; font-weight:700; color:#e11d48; text-transform:uppercase; }
  .xp-text { font-size:12px; color:#444; line-height:1.7; margin-top:4px; }
</style></head>
<body>
<div class="head">
  <div><h1>${d.name}</h1><div class="role">${d.role}</div></div>
  <div class="contacts">${[d.email, d.phone, d.linkedin, d.github].filter(Boolean).join('<br>')}</div>
</div>
<div class="grid">
  <div>
    ${d.summary ? `<div class="sec"><div class="sec-title">Profile</div><p class="summary">${d.summary}</p></div>` : ''}
    ${d.skills?.length ? `<div class="sec"><div class="sec-title">Skills</div>${d.skills.map(s => `<span class="skill">${s}</span>`).join('')}</div>` : ''}
    ${d.education?.length ? `<div class="sec"><div class="sec-title">Education</div>${d.education.map(e => `<div class="edu"><b>${e.degree}</b><span>${e.school}</span></div>`).join('')}</div>` : ''}
    ${d.extra ? `<div class="sec"><div class="sec-title">Other</div><div class="xp-text">${d.extra}</div></div>` : ''}
  </div>
  <div>
    ${d.experience?.length ? `<div class="sec"><div class="sec-title">Experience</div>${d.experience.map(e => `<div class="xp"><div class="xp-head"><span class="xp-title">${e.title}</span><span class="xp-co">${e.company}</span></div><div class="xp-text">${e.description}</div></div>`).join('')}</div>` : ''}
    ${d.projects?.length ? `<div class="sec"><div class="sec-title">Projects</div>${d.projects.map(p => `<div class="xp"><div class="xp-title">${p.name}</div><div class="xp-text">${p.description}</div></div>`).join('')}</div>` : ''}
  </div>
</div>
</body></html>`
  },
};

// Parse resume text into structured data using AI
export const parseResumeData = async (text, generateFieldContent) => {
  const prompt = `Extract resume information from this text and return ONLY a valid JSON object.

Resume Text:
${text}

Return this exact JSON structure (fill with extracted data, empty arrays if not found):
{
  "name": "Full Name",
  "role": "Job Title/Role",
  "email": "email@example.com",
  "phone": "+91-XXXXX-XXXXX",
  "linkedin": "",
  "github": "",
  "summary": "Professional summary paragraph",
  "skills": ["Skill1", "Skill2", "Skill3"],
  "experience": [
    {"title": "Job Title", "company": "Company Name", "description": "What they did"}
  ],
  "education": [
    {"degree": "Degree Name", "school": "University, Year, CGPA"}
  ],
  "projects": [
    {"name": "Project Name", "description": "What it does"}
  ],
  "extra": "Any other info like certifications, languages, hobbies"
}

IMPORTANT: Return ONLY the JSON object, no markdown, no explanation.`;

  const res = await generateFieldContent(prompt);
  let raw = res.data.result?.trim() || '{}';
  raw = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```$/i, '').trim();

  try {
    return JSON.parse(raw);
  } catch {
    return {
      name: 'Name Not Found', role: 'Role', email: '', phone: '',
      linkedin: '', github: '', summary: text.substring(0, 200),
      skills: [], experience: [], education: [], projects: [], extra: ''
    };
  }
};